/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * wanaku-router-backend API
 * OpenAPI spec version: 0.0.9-SNAPSHOT
 */
import type {
  DataStore,
  DeleteApiV1DataStoreByLabelParams,
  DeleteApiV1DataStoreByNameParams,
  DeleteApiV1PromptsParams,
  DeleteApiV1ResourcesParams,
  DeleteApiV1ToolsByLabelParams,
  DeleteApiV1ToolsParams,
  ForwardReference,
  GetApiV1DataStoreByNameParams,
  GetApiV1DataStoreParams,
  GetApiV1ForwardsParams,
  GetApiV1NamespacesParams,
  GetApiV1ResourcesParams,
  GetApiV1ToolsParams,
  Namespace,
  OutboundSseEvent,
  PromptPayload,
  PromptReference,
  ResourcePayload,
  ResourceReference,
  ServiceState,
  ServiceTarget,
  ToolPayload,
  ToolReference,
  WanakuResponse,
  WanakuResponseDataStore,
  WanakuResponseForwardReference,
  WanakuResponseInteger,
  WanakuResponseListDataStore,
  WanakuResponseListForwardReference,
  WanakuResponseListNamespace,
  WanakuResponseListPromptReference,
  WanakuResponseListResourceReference,
  WanakuResponseListServiceTarget,
  WanakuResponseListToolReference,
  WanakuResponseMapStringListActivityRecord,
  WanakuResponseNamespace,
  WanakuResponsePromptReference,
  WanakuResponseResourceReference,
  WanakuResponseServerInfo,
  WanakuResponseServiceTarget,
  WanakuResponseToolReference,
} from "../models";

import { customFetch } from "../custom-fetch";
/**
 * @summary List
 */
export type getApiV1CapabilitiesResponse200 = {
  data: WanakuResponseListServiceTarget;
  status: 200;
};

export type getApiV1CapabilitiesResponseComposite =
  getApiV1CapabilitiesResponse200;

export type getApiV1CapabilitiesResponse =
  getApiV1CapabilitiesResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesUrl = () => {
  return `/api/v1/capabilities`;
};

export const getApiV1Capabilities = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResponse> => {
  return customFetch<getApiV1CapabilitiesResponse>(
    getGetApiV1CapabilitiesUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Targets Event Stream
 */
export type getApiV1CapabilitiesNotificationsResponse200 = {
  data: OutboundSseEvent[];
  status: 200;
};

export type getApiV1CapabilitiesNotificationsResponseComposite =
  getApiV1CapabilitiesNotificationsResponse200;

export type getApiV1CapabilitiesNotificationsResponse =
  getApiV1CapabilitiesNotificationsResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesNotificationsUrl = () => {
  return `/api/v1/capabilities/notifications`;
};

export const getApiV1CapabilitiesNotifications = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesNotificationsResponse> => {
  return customFetch<getApiV1CapabilitiesNotificationsResponse>(
    getGetApiV1CapabilitiesNotificationsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Resources State
 */
export type getApiV1CapabilitiesResourcesStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesResourcesStateResponseComposite =
  getApiV1CapabilitiesResourcesStateResponse200;

export type getApiV1CapabilitiesResourcesStateResponse =
  getApiV1CapabilitiesResourcesStateResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesResourcesStateUrl = () => {
  return `/api/v1/capabilities/resources/state`;
};

export const getApiV1CapabilitiesResourcesState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesResourcesStateResponse> => {
  return customFetch<getApiV1CapabilitiesResourcesStateResponse>(
    getGetApiV1CapabilitiesResourcesStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Tools State
 */
export type getApiV1CapabilitiesToolsStateResponse200 = {
  data: WanakuResponseMapStringListActivityRecord;
  status: 200;
};

export type getApiV1CapabilitiesToolsStateResponseComposite =
  getApiV1CapabilitiesToolsStateResponse200;

export type getApiV1CapabilitiesToolsStateResponse =
  getApiV1CapabilitiesToolsStateResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1CapabilitiesToolsStateUrl = () => {
  return `/api/v1/capabilities/tools/state`;
};

export const getApiV1CapabilitiesToolsState = async (
  options?: RequestInit,
): Promise<getApiV1CapabilitiesToolsStateResponse> => {
  return customFetch<getApiV1CapabilitiesToolsStateResponse>(
    getGetApiV1CapabilitiesToolsStateUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1DataStoreResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1DataStoreResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1DataStoreResponseComposite =
  | putApiV1DataStoreResponse200
  | putApiV1DataStoreResponse400
  | putApiV1DataStoreResponse500;

export type putApiV1DataStoreResponse = putApiV1DataStoreResponseComposite & {
  headers: Headers;
};

export const getPutApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const putApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<putApiV1DataStoreResponse> => {
  return customFetch<putApiV1DataStoreResponse>(getPutApiV1DataStoreUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary List
 */
export type getApiV1DataStoreResponse200 = {
  data: WanakuResponseListDataStore;
  status: 200;
};

export type getApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1DataStoreResponseComposite =
  | getApiV1DataStoreResponse200
  | getApiV1DataStoreResponse500;

export type getApiV1DataStoreResponse = getApiV1DataStoreResponseComposite & {
  headers: Headers;
};

export const getGetApiV1DataStoreUrl = (params?: GetApiV1DataStoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const getApiV1DataStore = async (
  params?: GetApiV1DataStoreParams,
  options?: RequestInit,
): Promise<getApiV1DataStoreResponse> => {
  return customFetch<getApiV1DataStoreResponse>(
    getGetApiV1DataStoreUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Add
 */
export type postApiV1DataStoreResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1DataStoreResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1DataStoreResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1DataStoreResponseComposite =
  | postApiV1DataStoreResponse200
  | postApiV1DataStoreResponse400
  | postApiV1DataStoreResponse500;

export type postApiV1DataStoreResponse = postApiV1DataStoreResponseComposite & {
  headers: Headers;
};

export const getPostApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const postApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1DataStoreResponse> => {
  return customFetch<postApiV1DataStoreResponse>(getPostApiV1DataStoreUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove If
 */
export type deleteApiV1DataStoreByLabelResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1DataStoreByLabelResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreByLabelResponseComposite =
  | deleteApiV1DataStoreByLabelResponse200
  | deleteApiV1DataStoreByLabelResponse500;

export type deleteApiV1DataStoreByLabelResponse =
  deleteApiV1DataStoreByLabelResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1DataStoreByLabelUrl = (
  params?: DeleteApiV1DataStoreByLabelParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/by-label?${stringifiedParams}`
    : `/api/v1/data-store/by-label`;
};

export const deleteApiV1DataStoreByLabel = async (
  params?: DeleteApiV1DataStoreByLabelParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreByLabelResponse> => {
  return customFetch<deleteApiV1DataStoreByLabelResponse>(
    getDeleteApiV1DataStoreByLabelUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Remove By Name
 */
export type deleteApiV1DataStoreByNameResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1DataStoreByNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreByNameResponseComposite =
  | deleteApiV1DataStoreByNameResponse200
  | deleteApiV1DataStoreByNameResponse500;

export type deleteApiV1DataStoreByNameResponse =
  deleteApiV1DataStoreByNameResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1DataStoreByNameUrl = (
  params?: DeleteApiV1DataStoreByNameParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/by-name?${stringifiedParams}`
    : `/api/v1/data-store/by-name`;
};

export const deleteApiV1DataStoreByName = async (
  params?: DeleteApiV1DataStoreByNameParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreByNameResponse> => {
  return customFetch<deleteApiV1DataStoreByNameResponse>(
    getDeleteApiV1DataStoreByNameUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1DataStoreByNameResponse200 = {
  data: WanakuResponseListDataStore;
  status: 200;
};

export type getApiV1DataStoreByNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1DataStoreByNameResponseComposite =
  | getApiV1DataStoreByNameResponse200
  | getApiV1DataStoreByNameResponse500;

export type getApiV1DataStoreByNameResponse =
  getApiV1DataStoreByNameResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1DataStoreByNameUrl = (
  params?: GetApiV1DataStoreByNameParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/by-name?${stringifiedParams}`
    : `/api/v1/data-store/by-name`;
};

export const getApiV1DataStoreByName = async (
  params?: GetApiV1DataStoreByNameParams,
  options?: RequestInit,
): Promise<getApiV1DataStoreByNameResponse> => {
  return customFetch<getApiV1DataStoreByNameResponse>(
    getGetApiV1DataStoreByNameUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1DataStoreIdResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1DataStoreIdResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1DataStoreIdResponseComposite =
  | deleteApiV1DataStoreIdResponse200
  | deleteApiV1DataStoreIdResponse500;

export type deleteApiV1DataStoreIdResponse =
  deleteApiV1DataStoreIdResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const deleteApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreIdResponse> => {
  return customFetch<deleteApiV1DataStoreIdResponse>(
    getDeleteApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1DataStoreIdResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1DataStoreIdResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1DataStoreIdResponseComposite =
  | getApiV1DataStoreIdResponse200
  | getApiV1DataStoreIdResponse500;

export type getApiV1DataStoreIdResponse =
  getApiV1DataStoreIdResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const getApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1DataStoreIdResponse> => {
  return customFetch<getApiV1DataStoreIdResponse>(
    getGetApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ForwardsResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ForwardsResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ForwardsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ForwardsResponseComposite =
  | putApiV1ForwardsResponse200
  | putApiV1ForwardsResponse400
  | putApiV1ForwardsResponse500;

export type putApiV1ForwardsResponse = putApiV1ForwardsResponseComposite & {
  headers: Headers;
};

export const getPutApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const putApiV1Forwards = async (
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<putApiV1ForwardsResponse> => {
  return customFetch<putApiV1ForwardsResponse>(getPutApiV1ForwardsUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardReference),
  });
};

/**
 * @summary Remove Forward
 */
export type deleteApiV1ForwardsResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ForwardsResponseComposite =
  deleteApiV1ForwardsResponse200;

export type deleteApiV1ForwardsResponse =
  deleteApiV1ForwardsResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const deleteApiV1Forwards = async (
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<deleteApiV1ForwardsResponse> => {
  return customFetch<deleteApiV1ForwardsResponse>(getDeleteApiV1ForwardsUrl(), {
    ...options,
    method: "DELETE",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardReference),
  });
};

/**
 * @summary List Forwards
 */
export type getApiV1ForwardsResponse200 = {
  data: WanakuResponseListForwardReference;
  status: 200;
};

export type getApiV1ForwardsResponseComposite = getApiV1ForwardsResponse200;

export type getApiV1ForwardsResponse = getApiV1ForwardsResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ForwardsUrl = (params?: GetApiV1ForwardsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/forwards?${stringifiedParams}`
    : `/api/v1/forwards`;
};

export const getApiV1Forwards = async (
  params?: GetApiV1ForwardsParams,
  options?: RequestInit,
): Promise<getApiV1ForwardsResponse> => {
  return customFetch<getApiV1ForwardsResponse>(getGetApiV1ForwardsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add Forward
 */
export type postApiV1ForwardsResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ForwardsResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ForwardsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ForwardsResponseComposite =
  | postApiV1ForwardsResponse200
  | postApiV1ForwardsResponse400
  | postApiV1ForwardsResponse500;

export type postApiV1ForwardsResponse = postApiV1ForwardsResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ForwardsUrl = () => {
  return `/api/v1/forwards`;
};

export const postApiV1Forwards = async (
  forwardReference: ForwardReference,
  options?: RequestInit,
): Promise<postApiV1ForwardsResponse> => {
  return customFetch<postApiV1ForwardsResponse>(getPostApiV1ForwardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(forwardReference),
  });
};

/**
 * @summary Get By Name
 */
export type getApiV1ForwardsNameResponse200 = {
  data: WanakuResponseForwardReference;
  status: 200;
};

export type getApiV1ForwardsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ForwardsNameResponseComposite =
  | getApiV1ForwardsNameResponse200
  | getApiV1ForwardsNameResponse500;

export type getApiV1ForwardsNameResponse =
  getApiV1ForwardsNameResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1ForwardsNameUrl = (name: string) => {
  return `/api/v1/forwards/${name}`;
};

export const getApiV1ForwardsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ForwardsNameResponse> => {
  return customFetch<getApiV1ForwardsNameResponse>(
    getGetApiV1ForwardsNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deregister
 */
export type postApiV1ManagementDiscoveryDeregisterResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryDeregisterResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryDeregisterResponseComposite =
  | postApiV1ManagementDiscoveryDeregisterResponse200
  | postApiV1ManagementDiscoveryDeregisterResponse400;

export type postApiV1ManagementDiscoveryDeregisterResponse =
  postApiV1ManagementDiscoveryDeregisterResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryDeregisterUrl = () => {
  return `/api/v1/management/discovery/deregister`;
};

export const postApiV1ManagementDiscoveryDeregister = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryDeregisterResponse> => {
  return customFetch<postApiV1ManagementDiscoveryDeregisterResponse>(
    getPostApiV1ManagementDiscoveryDeregisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @summary Ping
 */
export type postApiV1ManagementDiscoveryPingResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryPingResponseComposite =
  postApiV1ManagementDiscoveryPingResponse200;

export type postApiV1ManagementDiscoveryPingResponse =
  postApiV1ManagementDiscoveryPingResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryPingUrl = () => {
  return `/api/v1/management/discovery/ping`;
};

export const postApiV1ManagementDiscoveryPing = async (
  postApiV1ManagementDiscoveryPingBody: string,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryPingResponse> => {
  return customFetch<postApiV1ManagementDiscoveryPingResponse>(
    getPostApiV1ManagementDiscoveryPingUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postApiV1ManagementDiscoveryPingBody),
    },
  );
};

/**
 * @summary Register
 */
export type postApiV1ManagementDiscoveryRegisterResponse200 = {
  data: WanakuResponseServiceTarget;
  status: 200;
};

export type postApiV1ManagementDiscoveryRegisterResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryRegisterResponseComposite =
  | postApiV1ManagementDiscoveryRegisterResponse200
  | postApiV1ManagementDiscoveryRegisterResponse400;

export type postApiV1ManagementDiscoveryRegisterResponse =
  postApiV1ManagementDiscoveryRegisterResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryRegisterUrl = () => {
  return `/api/v1/management/discovery/register`;
};

export const postApiV1ManagementDiscoveryRegister = async (
  serviceTarget: ServiceTarget,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryRegisterResponse> => {
  return customFetch<postApiV1ManagementDiscoveryRegisterResponse>(
    getPostApiV1ManagementDiscoveryRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceTarget),
    },
  );
};

/**
 * @summary Update State
 */
export type postApiV1ManagementDiscoveryUpdateIdResponse200 = {
  data: null;
  status: 200;
};

export type postApiV1ManagementDiscoveryUpdateIdResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ManagementDiscoveryUpdateIdResponseComposite =
  | postApiV1ManagementDiscoveryUpdateIdResponse200
  | postApiV1ManagementDiscoveryUpdateIdResponse400;

export type postApiV1ManagementDiscoveryUpdateIdResponse =
  postApiV1ManagementDiscoveryUpdateIdResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ManagementDiscoveryUpdateIdUrl = (id: string) => {
  return `/api/v1/management/discovery/update/${id}`;
};

export const postApiV1ManagementDiscoveryUpdateId = async (
  id: string,
  serviceState: ServiceState,
  options?: RequestInit,
): Promise<postApiV1ManagementDiscoveryUpdateIdResponse> => {
  return customFetch<postApiV1ManagementDiscoveryUpdateIdResponse>(
    getPostApiV1ManagementDiscoveryUpdateIdUrl(id),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(serviceState),
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ManagementInfoVersionResponse200 = {
  data: WanakuResponseServerInfo;
  status: 200;
};

export type getApiV1ManagementInfoVersionResponseComposite =
  getApiV1ManagementInfoVersionResponse200;

export type getApiV1ManagementInfoVersionResponse =
  getApiV1ManagementInfoVersionResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1ManagementInfoVersionUrl = () => {
  return `/api/v1/management/info/version`;
};

export const getApiV1ManagementInfoVersion = async (
  options?: RequestInit,
): Promise<getApiV1ManagementInfoVersionResponse> => {
  return customFetch<getApiV1ManagementInfoVersionResponse>(
    getGetApiV1ManagementInfoVersionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1NamespacesResponse200 = {
  data: WanakuResponseListNamespace;
  status: 200;
};

export type getApiV1NamespacesResponseComposite = getApiV1NamespacesResponse200;

export type getApiV1NamespacesResponse = getApiV1NamespacesResponseComposite & {
  headers: Headers;
};

export const getGetApiV1NamespacesUrl = (params?: GetApiV1NamespacesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/namespaces?${stringifiedParams}`
    : `/api/v1/namespaces`;
};

export const getApiV1Namespaces = async (
  params?: GetApiV1NamespacesParams,
  options?: RequestInit,
): Promise<getApiV1NamespacesResponse> => {
  return customFetch<getApiV1NamespacesResponse>(
    getGetApiV1NamespacesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1NamespacesIdResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1NamespacesIdResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1NamespacesIdResponseComposite =
  | putApiV1NamespacesIdResponse200
  | putApiV1NamespacesIdResponse400;

export type putApiV1NamespacesIdResponse =
  putApiV1NamespacesIdResponseComposite & {
    headers: Headers;
  };

export const getPutApiV1NamespacesIdUrl = (id: string) => {
  return `/api/v1/namespaces/${id}`;
};

export const putApiV1NamespacesId = async (
  id: string,
  namespace: Namespace,
  options?: RequestInit,
): Promise<putApiV1NamespacesIdResponse> => {
  return customFetch<putApiV1NamespacesIdResponse>(
    getPutApiV1NamespacesIdUrl(id),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(namespace),
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1NamespacesIdResponse200 = {
  data: WanakuResponseNamespace;
  status: 200;
};

export type getApiV1NamespacesIdResponseComposite =
  getApiV1NamespacesIdResponse200;

export type getApiV1NamespacesIdResponse =
  getApiV1NamespacesIdResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1NamespacesIdUrl = (id: string) => {
  return `/api/v1/namespaces/${id}`;
};

export const getApiV1NamespacesId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1NamespacesIdResponse> => {
  return customFetch<getApiV1NamespacesIdResponse>(
    getGetApiV1NamespacesIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1PromptsResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1PromptsResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1PromptsResponseComposite =
  | putApiV1PromptsResponse200
  | putApiV1PromptsResponse400
  | putApiV1PromptsResponse500;

export type putApiV1PromptsResponse = putApiV1PromptsResponseComposite & {
  headers: Headers;
};

export const getPutApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const putApiV1Prompts = async (
  promptReference: PromptReference,
  options?: RequestInit,
): Promise<putApiV1PromptsResponse> => {
  return customFetch<putApiV1PromptsResponse>(getPutApiV1PromptsUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(promptReference),
  });
};

/**
 * @summary Remove
 */
export type deleteApiV1PromptsResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1PromptsResponseComposite =
  | deleteApiV1PromptsResponse200
  | deleteApiV1PromptsResponse500;

export type deleteApiV1PromptsResponse = deleteApiV1PromptsResponseComposite & {
  headers: Headers;
};

export const getDeleteApiV1PromptsUrl = (params?: DeleteApiV1PromptsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/prompts?${stringifiedParams}`
    : `/api/v1/prompts`;
};

export const deleteApiV1Prompts = async (
  params?: DeleteApiV1PromptsParams,
  options?: RequestInit,
): Promise<deleteApiV1PromptsResponse> => {
  return customFetch<deleteApiV1PromptsResponse>(
    getDeleteApiV1PromptsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1PromptsResponse200 = {
  data: WanakuResponseListPromptReference;
  status: 200;
};

export type getApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1PromptsResponseComposite =
  | getApiV1PromptsResponse200
  | getApiV1PromptsResponse500;

export type getApiV1PromptsResponse = getApiV1PromptsResponseComposite & {
  headers: Headers;
};

export const getGetApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const getApiV1Prompts = async (
  options?: RequestInit,
): Promise<getApiV1PromptsResponse> => {
  return customFetch<getApiV1PromptsResponse>(getGetApiV1PromptsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add
 */
export type postApiV1PromptsResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type postApiV1PromptsResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1PromptsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1PromptsResponseComposite =
  | postApiV1PromptsResponse200
  | postApiV1PromptsResponse400
  | postApiV1PromptsResponse500;

export type postApiV1PromptsResponse = postApiV1PromptsResponseComposite & {
  headers: Headers;
};

export const getPostApiV1PromptsUrl = () => {
  return `/api/v1/prompts`;
};

export const postApiV1Prompts = async (
  promptReference: PromptReference,
  options?: RequestInit,
): Promise<postApiV1PromptsResponse> => {
  return customFetch<postApiV1PromptsResponse>(getPostApiV1PromptsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(promptReference),
  });
};

/**
 * @summary Add With Payload
 */
export type postApiV1PromptsWithPayloadResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type postApiV1PromptsWithPayloadResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1PromptsWithPayloadResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1PromptsWithPayloadResponseComposite =
  | postApiV1PromptsWithPayloadResponse200
  | postApiV1PromptsWithPayloadResponse400
  | postApiV1PromptsWithPayloadResponse500;

export type postApiV1PromptsWithPayloadResponse =
  postApiV1PromptsWithPayloadResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1PromptsWithPayloadUrl = () => {
  return `/api/v1/prompts/with-payload`;
};

export const postApiV1PromptsWithPayload = async (
  promptPayload: PromptPayload,
  options?: RequestInit,
): Promise<postApiV1PromptsWithPayloadResponse> => {
  return customFetch<postApiV1PromptsWithPayloadResponse>(
    getPostApiV1PromptsWithPayloadUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(promptPayload),
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1PromptsNameResponse200 = {
  data: WanakuResponsePromptReference;
  status: 200;
};

export type getApiV1PromptsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1PromptsNameResponseComposite =
  | getApiV1PromptsNameResponse200
  | getApiV1PromptsNameResponse500;

export type getApiV1PromptsNameResponse =
  getApiV1PromptsNameResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1PromptsNameUrl = (name: string) => {
  return `/api/v1/prompts/${name}`;
};

export const getApiV1PromptsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1PromptsNameResponse> => {
  return customFetch<getApiV1PromptsNameResponse>(
    getGetApiV1PromptsNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ResourcesResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ResourcesResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ResourcesResponseComposite =
  | putApiV1ResourcesResponse200
  | putApiV1ResourcesResponse400
  | putApiV1ResourcesResponse500;

export type putApiV1ResourcesResponse = putApiV1ResourcesResponseComposite & {
  headers: Headers;
};

export const getPutApiV1ResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const putApiV1Resources = async (
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<putApiV1ResourcesResponse> => {
  return customFetch<putApiV1ResourcesResponse>(getPutApiV1ResourcesUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(resourceReference),
  });
};

/**
 * @summary Remove
 */
export type deleteApiV1ResourcesResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ResourcesResponseComposite =
  | deleteApiV1ResourcesResponse200
  | deleteApiV1ResourcesResponse500;

export type deleteApiV1ResourcesResponse =
  deleteApiV1ResourcesResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ResourcesUrl = (
  params?: DeleteApiV1ResourcesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/resources?${stringifiedParams}`
    : `/api/v1/resources`;
};

export const deleteApiV1Resources = async (
  params?: DeleteApiV1ResourcesParams,
  options?: RequestInit,
): Promise<deleteApiV1ResourcesResponse> => {
  return customFetch<deleteApiV1ResourcesResponse>(
    getDeleteApiV1ResourcesUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ResourcesResponse200 = {
  data: WanakuResponseListResourceReference;
  status: 200;
};

export type getApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ResourcesResponseComposite =
  | getApiV1ResourcesResponse200
  | getApiV1ResourcesResponse500;

export type getApiV1ResourcesResponse = getApiV1ResourcesResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ResourcesUrl = (params?: GetApiV1ResourcesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/resources?${stringifiedParams}`
    : `/api/v1/resources`;
};

export const getApiV1Resources = async (
  params?: GetApiV1ResourcesParams,
  options?: RequestInit,
): Promise<getApiV1ResourcesResponse> => {
  return customFetch<getApiV1ResourcesResponse>(
    getGetApiV1ResourcesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Expose
 */
export type postApiV1ResourcesResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ResourcesResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesResponseComposite =
  | postApiV1ResourcesResponse200
  | postApiV1ResourcesResponse400
  | postApiV1ResourcesResponse500;

export type postApiV1ResourcesResponse = postApiV1ResourcesResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ResourcesUrl = () => {
  return `/api/v1/resources`;
};

export const postApiV1Resources = async (
  resourceReference: ResourceReference,
  options?: RequestInit,
): Promise<postApiV1ResourcesResponse> => {
  return customFetch<postApiV1ResourcesResponse>(getPostApiV1ResourcesUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(resourceReference),
  });
};

/**
 * @summary Expose With Payload
 */
export type postApiV1ResourcesWithPayloadResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type postApiV1ResourcesWithPayloadResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ResourcesWithPayloadResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ResourcesWithPayloadResponseComposite =
  | postApiV1ResourcesWithPayloadResponse200
  | postApiV1ResourcesWithPayloadResponse400
  | postApiV1ResourcesWithPayloadResponse500;

export type postApiV1ResourcesWithPayloadResponse =
  postApiV1ResourcesWithPayloadResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ResourcesWithPayloadUrl = () => {
  return `/api/v1/resources/with-payload`;
};

export const postApiV1ResourcesWithPayload = async (
  resourcePayload: ResourcePayload,
  options?: RequestInit,
): Promise<postApiV1ResourcesWithPayloadResponse> => {
  return customFetch<postApiV1ResourcesWithPayloadResponse>(
    getPostApiV1ResourcesWithPayloadUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(resourcePayload),
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ResourcesNameResponse200 = {
  data: WanakuResponseResourceReference;
  status: 200;
};

export type getApiV1ResourcesNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ResourcesNameResponseComposite =
  | getApiV1ResourcesNameResponse200
  | getApiV1ResourcesNameResponse500;

export type getApiV1ResourcesNameResponse =
  getApiV1ResourcesNameResponseComposite & {
    headers: Headers;
  };

export const getGetApiV1ResourcesNameUrl = (name: string) => {
  return `/api/v1/resources/${name}`;
};

export const getApiV1ResourcesName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ResourcesNameResponse> => {
  return customFetch<getApiV1ResourcesNameResponse>(
    getGetApiV1ResourcesNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update
 */
export type putApiV1ToolsResponse200 = {
  data: null;
  status: 200;
};

export type putApiV1ToolsResponse400 = {
  data: null;
  status: 400;
};

export type putApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type putApiV1ToolsResponseComposite =
  | putApiV1ToolsResponse200
  | putApiV1ToolsResponse400
  | putApiV1ToolsResponse500;

export type putApiV1ToolsResponse = putApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getPutApiV1ToolsUrl = () => {
  return `/api/v1/tools`;
};

export const putApiV1Tools = async (
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<putApiV1ToolsResponse> => {
  return customFetch<putApiV1ToolsResponse>(getPutApiV1ToolsUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toolReference),
  });
};

/**
 * @summary Remove
 */
export type deleteApiV1ToolsResponse200 = {
  data: null;
  status: 200;
};

export type deleteApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ToolsResponseComposite =
  | deleteApiV1ToolsResponse200
  | deleteApiV1ToolsResponse500;

export type deleteApiV1ToolsResponse = deleteApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getDeleteApiV1ToolsUrl = (params?: DeleteApiV1ToolsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tools?${stringifiedParams}`
    : `/api/v1/tools`;
};

export const deleteApiV1Tools = async (
  params?: DeleteApiV1ToolsParams,
  options?: RequestInit,
): Promise<deleteApiV1ToolsResponse> => {
  return customFetch<deleteApiV1ToolsResponse>(getDeleteApiV1ToolsUrl(params), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary List
 */
export type getApiV1ToolsResponse200 = {
  data: WanakuResponseListToolReference;
  status: 200;
};

export type getApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsResponseComposite =
  | getApiV1ToolsResponse200
  | getApiV1ToolsResponse500;

export type getApiV1ToolsResponse = getApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ToolsUrl = (params?: GetApiV1ToolsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tools?${stringifiedParams}`
    : `/api/v1/tools`;
};

export const getApiV1Tools = async (
  params?: GetApiV1ToolsParams,
  options?: RequestInit,
): Promise<getApiV1ToolsResponse> => {
  return customFetch<getApiV1ToolsResponse>(getGetApiV1ToolsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Add
 */
export type postApiV1ToolsResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ToolsResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsResponseComposite =
  | postApiV1ToolsResponse200
  | postApiV1ToolsResponse400
  | postApiV1ToolsResponse500;

export type postApiV1ToolsResponse = postApiV1ToolsResponseComposite & {
  headers: Headers;
};

export const getPostApiV1ToolsUrl = () => {
  return `/api/v1/tools`;
};

export const postApiV1Tools = async (
  toolReference: ToolReference,
  options?: RequestInit,
): Promise<postApiV1ToolsResponse> => {
  return customFetch<postApiV1ToolsResponse>(getPostApiV1ToolsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(toolReference),
  });
};

/**
 * @summary Remove If
 */
export type deleteApiV1ToolsByLabelResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1ToolsByLabelResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type deleteApiV1ToolsByLabelResponseComposite =
  | deleteApiV1ToolsByLabelResponse200
  | deleteApiV1ToolsByLabelResponse500;

export type deleteApiV1ToolsByLabelResponse =
  deleteApiV1ToolsByLabelResponseComposite & {
    headers: Headers;
  };

export const getDeleteApiV1ToolsByLabelUrl = (
  params?: DeleteApiV1ToolsByLabelParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/tools/by-label?${stringifiedParams}`
    : `/api/v1/tools/by-label`;
};

export const deleteApiV1ToolsByLabel = async (
  params?: DeleteApiV1ToolsByLabelParams,
  options?: RequestInit,
): Promise<deleteApiV1ToolsByLabelResponse> => {
  return customFetch<deleteApiV1ToolsByLabelResponse>(
    getDeleteApiV1ToolsByLabelUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Add With Payload
 */
export type postApiV1ToolsWithPayloadResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type postApiV1ToolsWithPayloadResponse400 = {
  data: null;
  status: 400;
};

export type postApiV1ToolsWithPayloadResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type postApiV1ToolsWithPayloadResponseComposite =
  | postApiV1ToolsWithPayloadResponse200
  | postApiV1ToolsWithPayloadResponse400
  | postApiV1ToolsWithPayloadResponse500;

export type postApiV1ToolsWithPayloadResponse =
  postApiV1ToolsWithPayloadResponseComposite & {
    headers: Headers;
  };

export const getPostApiV1ToolsWithPayloadUrl = () => {
  return `/api/v1/tools/with-payload`;
};

export const postApiV1ToolsWithPayload = async (
  toolPayload: ToolPayload,
  options?: RequestInit,
): Promise<postApiV1ToolsWithPayloadResponse> => {
  return customFetch<postApiV1ToolsWithPayloadResponse>(
    getPostApiV1ToolsWithPayloadUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(toolPayload),
    },
  );
};

/**
 * @summary Get By Name
 */
export type getApiV1ToolsNameResponse200 = {
  data: WanakuResponseToolReference;
  status: 200;
};

export type getApiV1ToolsNameResponse500 = {
  data: WanakuResponse;
  status: 500;
};

export type getApiV1ToolsNameResponseComposite =
  | getApiV1ToolsNameResponse200
  | getApiV1ToolsNameResponse500;

export type getApiV1ToolsNameResponse = getApiV1ToolsNameResponseComposite & {
  headers: Headers;
};

export const getGetApiV1ToolsNameUrl = (name: string) => {
  return `/api/v1/tools/${name}`;
};

export const getApiV1ToolsName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ToolsNameResponse> => {
  return customFetch<getApiV1ToolsNameResponse>(getGetApiV1ToolsNameUrl(name), {
    ...options,
    method: "GET",
  });
};
