version: '3'

services:
  wanaku-tool-service-http:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-tool-service-http:wanaku-0.0.5
    ports:
      - "9000:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-tool-service-yaml-route:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-tool-service-yaml-route:wanaku-0.0.5
    ports:
      - "9001:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-tool-service-kafka:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-tool-service-kafka:wanaku-0.0.5
    ports:
      - "9003:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-tool-service-tavily:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-tool-service-tavily:wanaku-0.0.5
    #    environment:
    #      TAVILY_API_KEY: include-you-api-key-here
    ports:
      - "9006:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-provider-file:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-provider-file:wanaku-0.0.5
    ports:
      - "9002:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-provider-ftp:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-provider-ftp:wanaku-0.0.5
    ports:
      - "9004:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  # Uncomment the lines below to enable access to AWS S3
  wanaku-provider-s3:
    depends_on:
      - wanaku-router
    image: quay.io/wanaku/wanaku-provider-s3:wanaku-0.0.5
    ports:
      - "9005:9000"
    volumes:
      - wanaku-services:/home/default/.wanaku/services

  wanaku-router:
    image: quay.io/wanaku/wanaku-router:wanaku-0.0.5
    volumes:
      - wanaku-router:/home/default/.wanaku/router
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -f localhost:8080/api/v1/management/info/version || exit 1
      interval: 10s
      timeout: 10s
      retries: 5