version: '3'

services:
  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"

  wanaku-tool-service-http:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-tool-service-http:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9000:9000"
  wanaku-tool-service-yaml-route:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-tool-service-yaml-route:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9001:9000"

  # Uncomment if you want to enable Kafka
  wanaku-tool-service-kafka:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-tool-service-kafka:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9003:9000"

  wanaku-tool-service-tavily:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-tool-service-tavily:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
#      TAVILY_API_KEY: include-you-api-key-here
    ports:
      - "9006:9000"

  wanaku-provider-file:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-provider-file:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9002:9000"

  wanaku-provider-ftp:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-provider-ftp:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9004:9000"

  # Uncomment the lines below to enable access to AWS S3
  wanaku-provider-s3:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-provider-s3:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "9005:9000"

  wanaku-router:
    depends_on:
      - valkey
    image: quay.io/wanaku/wanaku-router:wanaku-0.0.5
    environment:
      WANAKU_SERVICE_PERSISTENCE: valkey
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      VALKEY_TIMEOUT: 10
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -f localhost:8080/api/v1/management/info/version || exit 1
      interval: 10s
      timeout: 10s
      retries: 5