apiVersion: v1
data:
  AUTH_PROXY: http://wanaku-router-backend-orp-wanaku.camel-dev-eu-de-1-bx2-4x1-b0521fcfdb6f3f868b0758fbda095bbe-0000.eu-de.containers.appdomain.cloud
  AUTH_SERVER: http://keycloak-orp-wanaku.camel-dev-eu-de-1-bx2-4x1-b0521fcfdb6f3f868b0758fbda095bbe-0000.eu-de.containers.appdomain.cloud
  QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED: "true"
  QUARKUS_OIDC_CREDENTIALS_SECRET: aBqsU3EzUPCHumf9sTK5sanxXkB0yFtv
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: wanaku
  name: wanaku-config
---
apiVersion: v1
data:
  AUTH_SERVER: http://keycloak-orp-wanaku.camel-dev-eu-de-1-bx2-4x1-b0521fcfdb6f3f868b0758fbda095bbe-0000.eu-de.containers.appdomain.cloud
  WANAKU_SERVICE_REGISTRATION_URI: http://wanaku-router-backend:8080/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: wanaku
  name: wanaku-services-config
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: wanaku
  name: wanaku-service-credentials
stringData:
  QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET: fjgE1vkb0x5UhXj8yrecwyOmRlYR9tR6
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wanaku-router-backend
    app.kubernetes.io/part-of: wanaku
  name: wanaku-router-backend
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: wanaku-router-backend
    app.kubernetes.io/part-of: wanaku
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wanaku-tool-service-http
    app.kubernetes.io/part-of: wanaku
  name: wanaku-tool-service-http
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: wanaku-tool-service-http
    app.kubernetes.io/part-of: wanaku
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wanaku-tool-service-tavily
    app.kubernetes.io/part-of: wanaku
  name: wanaku-tool-service-tavily
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: wanaku-tool-service-tavily
    app.kubernetes.io/part-of: wanaku
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wanaku-router-backend
    app.kubernetes.io/part-of: wanaku
  name: wanaku-router-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanaku-router-backend
      app.kubernetes.io/part-of: wanaku
  template:
    metadata:
      labels:
        app: wanaku-router-backend
        app.kubernetes.io/part-of: wanaku
    spec:
      containers:
      - env:
        - name: AUTH_SERVER
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER
              name: wanaku-config
        - name: AUTH_PROXY
          valueFrom:
            configMapKeyRef:
              key: AUTH_PROXY
              name: wanaku-config
        - name: QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED
          valueFrom:
            configMapKeyRef:
              key: QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED
              name: wanaku-config
        image: quay.io/orpiske/wanaku-router-backend:main
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/v1/management/info/version
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        name: wanaku-router-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/management/info/version
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /home/default/.wanaku/router
          name: router-volume
      volumes:
      - emptyDir: {}
        name: router-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wanaku-tool-service-http
    app.kubernetes.io/part-of: wanaku
  name: wanaku-tool-service-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanaku-tool-service-http
      app.kubernetes.io/part-of: wanaku
  template:
    metadata:
      labels:
        app: wanaku-tool-service-http
        app.kubernetes.io/part-of: wanaku
    spec:
      containers:
      - env:
        - name: AUTH_SERVER
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER
              name: wanaku-services-config
        - name: WANAKU_SERVICE_REGISTRATION_URI
          valueFrom:
            configMapKeyRef:
              key: WANAKU_SERVICE_REGISTRATION_URI
              name: wanaku-services-config
        - name: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              key: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
              name: wanaku-service-credentials
        image: quay.io/orpiske/wanaku-tool-service-http:main
        imagePullPolicy: Always
        name: wanaku-tool-service-http
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - mountPath: /home/default/.wanaku/services
          name: services-volume
      volumes:
      - emptyDir: {}
        name: services-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wanaku-tool-service-tavily
    app.kubernetes.io/part-of: wanaku
  name: wanaku-tool-service-tavily
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanaku-tool-service-tavily
      app.kubernetes.io/part-of: wanaku
  template:
    metadata:
      labels:
        app: wanaku-tool-service-tavily
        app.kubernetes.io/part-of: wanaku
    spec:
      containers:
      - env:
        - name: AUTH_SERVER
          valueFrom:
            configMapKeyRef:
              key: AUTH_SERVER
              name: wanaku-services-config
        - name: WANAKU_SERVICE_REGISTRATION_URI
          valueFrom:
            configMapKeyRef:
              key: WANAKU_SERVICE_REGISTRATION_URI
              name: wanaku-services-config
        - name: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              key: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
              name: wanaku-service-credentials
        image: quay.io/orpiske/wanaku-tool-service-tavily:main
        imagePullPolicy: Always
        name: wanaku-tool-service-tavily
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - mountPath: /home/default/.wanaku/services
          name: services-volume
      volumes:
      - emptyDir: {}
        name: services-volume
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wanaku-router-backend
    app.kubernetes.io/part-of: wanaku
  name: wanaku-router-backend
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: wanaku-router-backend
    weight: 100
  wildcardPolicy: None
